"use client";
import { useState } from "react";
import Link from "next/link";
import { useLocale, useTranslations } from "next-intl";
import { ArrowLeft, CheckCircle2, MapPin, Navigation, Package, Phone, Store, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { StatusBadge } from "@/features/delivery-company/components/status-badge";
import { DriverStatus } from "./driver-status";
import { useDeliverOrder, useDriverOrder, useFailOrder, useStartDelivery, useVerifyPickup } from "../use-driver";
import { getGoogleMapsDirectionsUrl } from "@/lib/maps";

export function DriverOrderDetails({ orderId }: { orderId: string }) {
  const t = useTranslations("Driver"); const locale = useLocale(); const { data, isLoading, isError, refetch } = useDriverOrder(orderId);
  const pickup = useVerifyPickup(); const start = useStartDelivery(); const deliver = useDeliverOrder(); const fail = useFailOrder();
  const [pickupCode, setPickupCode] = useState(""); const [completeOpen, setCompleteOpen] = useState(false); const [failOpen, setFailOpen] = useState(false); const [reason, setReason] = useState("");
  const money = (v: string) => new Intl.NumberFormat(locale === "ar" ? "ar-JO" : "en-JO", { style: "currency", currency: "JOD" }).format(Number(v));
  if (isLoading) return <Skeleton className="h-[38rem] rounded-3xl"/>;
  if (isError || !data) return <Card className="rounded-3xl"><CardContent className="flex min-h-64 flex-col items-center justify-center gap-4"><Package className="size-10 text-destructive"/><p>{t("common.loadError")}</p><Button onClick={() => refetch()}>{t("actions.retry")}</Button></CardContent></Card>;
  const order = data.order; const done = (message: string) => { toast.success(message); refetch(); };
  const labels = Object.fromEntries(["ACCEPTED", "PICKED_UP", "OUT_FOR_DELIVERY", "DELIVERED"].map(s => [s, t(`timeline.${s}`)]));
  return <div className="space-y-4"><Button variant="outline" className="rounded-full" render={<Link href={`/${locale}/driver/orders`}/>}><ArrowLeft className="size-4 rtl:rotate-180"/>{t("details.back")}</Button>
    <Card className="overflow-hidden rounded-3xl"><div className="h-1.5 bg-primary"/><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs text-muted-foreground">#{order.id.slice(0,8)}</p><CardTitle className="mt-2 text-xl">{order.customerName}</CardTitle></div><StatusBadge status={order.status} label={t(`statuses.${order.status}`)}/></div></CardHeader><CardContent><DriverStatus status={order.status} labels={labels}/></CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2"><ContactCard icon={Store} label={t("details.pickupFrom")} title={order.shopOwner.user.name} detail={order.shopOwner.user.phoneNumber} phone/><ContactCard icon={MapPin} label={t("details.deliverTo")} title={order.customerAddress} detail={order.customerPhone} phone/></div>
    <div className="grid gap-4 lg:grid-cols-[1fr_18rem]"><Card className="rounded-3xl"><CardHeader><CardTitle>{t("details.package")}</CardTitle></CardHeader><CardContent className="divide-y">{order.orderItems.map(item => <div key={item.id} className="flex justify-between gap-3 py-3 text-sm"><span>{item.product.name} × {item.quantity}</span><span className="font-medium">{money(String(Number(item.product.price)*item.quantity))}</span></div>)}<div className="flex justify-between pt-4 font-semibold"><span>{t("details.collect")}</span><span>{money(order.customerTotal)}</span></div>{order.customerNote && <div className="mt-4 pt-4"><p className="text-xs text-muted-foreground">{t("details.note")}</p><p className="mt-1 text-sm">{order.customerNote}</p></div>}</CardContent></Card>
      <Card className="rounded-3xl border-primary/15 bg-primary/[.035]"><CardHeader><CardTitle className="text-base">{t("details.nextAction")}</CardTitle></CardHeader><CardContent className="space-y-3">{order.status === "ACCEPTED" && <><p className="text-sm text-muted-foreground">{t("details.pickupHint")}</p><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={pickupCode} onChange={e => setPickupCode(e.target.value.replace(/\D/g, ""))} placeholder="000000" className="h-12 rounded-xl text-center font-mono text-xl tracking-[.35em]"/><Button className="w-full rounded-full" disabled={pickupCode.length !== 6 || pickup.isPending} onClick={() => pickup.mutate({ id: order.id, pickupCode }, { onSuccess: () => done(t("messages.pickedUp")), onError: () => toast.error(t("messages.pickupError")) })}>{t("actions.verifyPickup")}</Button></>}{order.status === "PICKED_UP" && <><p className="text-sm text-muted-foreground">{t("details.startHint")}</p><Button className="w-full rounded-full" disabled={start.isPending} onClick={() => start.mutate(order.id, { onSuccess: () => done(t("messages.started")), onError: () => toast.error(t("messages.actionError")) })}><Navigation className="size-4"/>{t("actions.start")}</Button></>}{order.status === "OUT_FOR_DELIVERY" && <><p className="text-sm text-muted-foreground">{t("details.completeHint")}</p><Button className="w-full rounded-full" onClick={() => setCompleteOpen(true)}><CheckCircle2 className="size-4"/>{t("actions.delivered")}</Button><Button variant="outline" className="w-full rounded-full border-destructive/30 text-destructive hover:text-destructive" onClick={() => setFailOpen(true)}><TriangleAlert className="size-4"/>{t("actions.failed")}</Button></>}{order.status === "FAILED" && <p className="text-sm text-muted-foreground">{t("details.returnHint")}</p>}{["DELIVERED","RETURNED","CANCELLED","REJECTED"].includes(order.status) && <p className="text-sm text-muted-foreground">{t("details.finished")}</p>}</CardContent></Card></div>
    <div className="grid gap-2 sm:grid-cols-2">{order.customerLatitude && order.customerLongitude && <Button className="h-11 rounded-full" render={<a href={getGoogleMapsDirectionsUrl(order.customerLatitude, order.customerLongitude)} target="_blank" rel="noreferrer"/>}><Navigation className="size-4"/>{t("actions.navigate")}</Button>}<Button variant="outline" className="h-11 rounded-full" render={<a href={`tel:${order.customerPhone}`}/>}><Phone className="size-4"/>{t("actions.callCustomer")}</Button></div>
    <Dialog open={completeOpen} onOpenChange={setCompleteOpen}><DialogContent className="rounded-3xl sm:max-w-sm"><DialogHeader><DialogTitle>{t("details.completeTitle")}</DialogTitle><DialogDescription>{t("details.completeDescription")}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" className="rounded-full" onClick={() => setCompleteOpen(false)}>{t("actions.cancel")}</Button><Button className="rounded-full" disabled={deliver.isPending} onClick={() => deliver.mutate(order.id, { onSuccess: () => { setCompleteOpen(false); done(t("messages.delivered")); }, onError: () => toast.error(t("messages.actionError")) })}>{t("actions.confirmDelivery")}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={failOpen} onOpenChange={setFailOpen}><DialogContent className="rounded-3xl sm:max-w-md"><DialogHeader><DialogTitle>{t("details.failTitle")}</DialogTitle><DialogDescription>{t("details.failDescription")}</DialogDescription></DialogHeader><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={5} maxLength={500} placeholder={t("details.failPlaceholder")} className="w-full resize-none rounded-xl border border-input bg-transparent px-3 py-2 text-sm outline-none focus:border-ring focus:ring-3 focus:ring-ring/30"/><DialogFooter><Button variant="outline" className="rounded-full" onClick={() => setFailOpen(false)}>{t("actions.cancel")}</Button><Button variant="destructive" className="rounded-full" disabled={!reason.trim() || fail.isPending} onClick={() => fail.mutate({ id: order.id, reason: reason.trim() }, { onSuccess: () => { setFailOpen(false); done(t("messages.failed")); }, onError: () => toast.error(t("messages.actionError")) })}>{t("actions.confirmFailure")}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function ContactCard({ icon: Icon, label, title, detail, phone }: { icon: typeof Store; label: string; title: string; detail: string; phone?: boolean }) { return <Card className="rounded-3xl"><CardContent className="flex gap-3 p-5"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="size-4"/></div><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate font-semibold">{title}</p>{phone ? <a href={`tel:${detail}`} className="mt-1 block text-sm text-primary" dir="ltr">{detail}</a> : <p className="mt-1 text-sm text-muted-foreground">{detail}</p>}</div></CardContent></Card>; }
