"use client";

import Link from "next/link";
import { useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { ArrowLeft, Building2, MapPin, Package, Phone, Truck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { useAcceptOrder, useAssignDriver, useCompanyOrder, useConfirmPayment, useDrivers, useRejectOrder } from "../use-delivery-company";
import { StatusBadge } from "./status-badge";
import { getGoogleMapsDirectionsUrl } from "@/lib/maps";

export function CompanyOrderDetails({ orderId }: { orderId: string }) {
  const t = useTranslations("DeliveryCompany"); const locale = useLocale(); const { data, isLoading, isError, refetch } = useCompanyOrder(orderId); const { data: drivers } = useDrivers();
  const accept = useAcceptOrder(); const reject = useRejectOrder(); const assign = useAssignDriver(); const payment = useConfirmPayment(); const [rejectOpen, setRejectOpen] = useState(false); const [reason, setReason] = useState("");
  const money = (v: string) => new Intl.NumberFormat(locale === "ar" ? "ar-JO" : "en-JO", { style: "currency", currency: "JOD", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(v));
  if (isLoading) return <Skeleton className="h-[35rem] rounded-3xl"/>;
  if (isError || !data) return <Card><CardContent className="flex min-h-64 flex-col items-center justify-center gap-4"><Package/><p>{t("common.loadError")}</p><Button onClick={() => refetch()}>{t("actions.retry")}</Button></CardContent></Card>;
  const order = data.order; const activeDrivers = drivers?.drivers.filter(d => d.user.isActive !== false) ?? [];
  const act = (mutation: typeof accept, success: string) => mutation.mutate(order.id, { onSuccess: () => { toast.success(success); refetch(); }, onError: () => toast.error(t("details.actionError")) });
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="outline" className="rounded-full" render={<Link href={`/${locale}/delivery-company/orders`} />}><ArrowLeft className="size-4 rtl:rotate-180"/>{t("details.back")}</Button><div className="flex gap-2">{order.status === "PENDING" && <><Button variant="outline" className="rounded-full border-destructive/30 text-destructive hover:bg-destructive/5 hover:text-destructive" onClick={() => setRejectOpen(true)}>{t("details.reject")}</Button><Button className="rounded-full" disabled={accept.isPending} onClick={() => act(accept, t("details.accepted"))}>{t("details.accept")}</Button></>}{order.status === "DELIVERED" && order.paymentStatus === "COLLECTED" && <Button className="rounded-full" disabled={payment.isPending} onClick={() => act(payment, t("details.paymentConfirmed"))}>{t("details.confirmPayment")}</Button>}</div></div>
    <Card className="overflow-hidden rounded-3xl"><div className="h-2 bg-primary"/><CardHeader className="flex flex-row items-start justify-between"><div><p className="font-mono text-xs text-muted-foreground">#{order.id.slice(0,8)}</p><CardTitle className="mt-2 text-2xl">{order.customerName}</CardTitle></div><StatusBadge status={order.status} label={t(`statuses.${order.status}`)}/></CardHeader><CardContent className="grid gap-5 lg:grid-cols-[1fr_.7fr]"><div className="grid gap-3 sm:grid-cols-2"><Info icon={Phone} label={t("details.phone")} value={order.customerPhone}/><Info icon={MapPin} label={t("details.address")} value={order.customerAddress}/><Info icon={Building2} label={t("details.shop")} value={order.shopOwner.user.name}/><Info icon={Truck} label={t("details.driver")} value={order.driver?.user.name ?? t("orders.unassigned")}/></div><div className="rounded-2xl bg-muted/50 p-5"><p className="text-sm font-medium">{t("details.financials")}</p><Line label={t("details.products")} value={money(order.totalPrice)}/><Line label={t("details.deliveryFee")} value={money(order.deliveryFee)}/><Line label={t("details.customerTotal")} value={money(order.customerTotal)} strong/></div></CardContent></Card>
    {order.status === "ACCEPTED" && !order.driver && <Card className="rounded-3xl"><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="size-5 text-primary"/>{t("details.assignTitle")}</CardTitle><p className="text-sm text-muted-foreground">{t("details.assignHint")}</p></CardHeader><CardContent><Select<string> disabled={assign.isPending || activeDrivers.length === 0} onValueChange={driverId => { if (driverId) assign.mutate({ id: order.id, driverId }, { onSuccess: () => { toast.success(t("details.assigned")); refetch(); }, onError: () => toast.error(t("details.actionError")) }); }}><SelectTrigger className="h-11 w-full rounded-xl sm:max-w-sm"><SelectValue placeholder={activeDrivers.length ? t("details.selectDriver") : t("details.noDrivers")}/></SelectTrigger><SelectContent>{activeDrivers.map(d => <SelectItem value={d.user.id} key={d.user.id}>{d.user.name} · {d.user.phoneNumber}</SelectItem>)}</SelectContent></Select></CardContent></Card>}
    {order.rejectionReason && <Card className="rounded-3xl border-rose-200 bg-rose-50/60 dark:border-rose-900 dark:bg-rose-950/20"><CardContent className="p-5"><p className="text-sm font-semibold text-rose-700 dark:text-rose-400">{t("details.rejectionReason")}</p><p className="mt-2 text-sm">{order.rejectionReason}</p></CardContent></Card>}
    <Card className="rounded-3xl"><CardHeader><CardTitle>{t("details.items")}</CardTitle></CardHeader><CardContent className="divide-y">{order.orderItems.map(item => <div className="flex items-center justify-between py-3" key={item.id}><span>{item.product.name} × {item.quantity}</span><span className="font-medium">{money(String(Number(item.product.price) * item.quantity))}</span></div>)}</CardContent></Card>
    {order.customerLatitude && order.customerLongitude && <Button variant="outline" className="rounded-full" render={<a href={getGoogleMapsDirectionsUrl(order.customerLatitude, order.customerLongitude)} target="_blank" rel="noreferrer"/>}><MapPin className="size-4"/>{t("details.openMap")}</Button>}
    <Dialog open={rejectOpen} onOpenChange={setRejectOpen}><DialogContent className="rounded-3xl sm:max-w-md"><DialogHeader><DialogTitle>{t("details.rejectTitle")}</DialogTitle><DialogDescription>{t("details.rejectHint")}</DialogDescription></DialogHeader><textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={500} rows={5} placeholder={t("details.reasonPlaceholder")} className="w-full resize-none rounded-xl border border-input bg-transparent px-3 py-2 text-sm outline-none transition focus:border-ring focus:ring-3 focus:ring-ring/30"/><DialogFooter><Button variant="outline" className="rounded-full" onClick={() => setRejectOpen(false)}>{t("details.keepOrder")}</Button><Button variant="destructive" className="rounded-full" disabled={!reason.trim() || reject.isPending} onClick={() => reject.mutate({ id: order.id, reason: reason.trim() }, { onSuccess: () => { toast.success(t("details.rejected")); setRejectOpen(false); refetch(); }, onError: () => toast.error(t("details.actionError")) })}>{reject.isPending ? t("details.rejecting") : t("details.confirmReject")}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function Info({ icon: Icon, label, value }: { icon: typeof Phone; label: string; value: string }) { return <div className="rounded-2xl border p-4"><Icon className="size-4 text-primary"/><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }
function Line({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between gap-3 py-2 text-sm ${strong ? "mt-2 border-t pt-4 font-semibold" : "text-muted-foreground"}`}><span>{label}</span><span className="text-foreground">{value}</span></div>; }
