"use client";
import { useDeferredValue, useState } from "react";
import Link from "next/link";
import { useLocale, useTranslations } from "next-intl";
import { ChevronLeft, ChevronRight, ClipboardList, Plus, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"; import { Skeleton } from "@/components/ui/skeleton";
import type { OrderStatus, PaymentStatus } from "@/features/admin/orders.types";
import { useShopOrders } from "../use-shop-owner";
const statuses: OrderStatus[] = ["PENDING", "ACCEPTED", "PICKED_UP", "OUT_FOR_DELIVERY", "DELIVERED", "FAILED", "RETURNED", "CANCELLED"];
const payments: PaymentStatus[] = ["PENDING", "COLLECTED", "PAID_TO_SHOP", "NOT_COLLECTED"];

export function ShopOrders() {
  const t = useTranslations("ShopOwner"); const locale = useLocale();
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const deferred = useDeferredValue(search); const [status, setStatus] = useState<OrderStatus | "ALL">("ALL"); const [payment, setPayment] = useState<PaymentStatus | "ALL">("ALL"); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState("");
  const { data, isLoading, isError, refetch } = useShopOrders({ page, limit: 10, search: deferred || undefined, status: status === "ALL" ? undefined : status, paymentStatus: payment === "ALL" ? undefined : payment, fromDate: fromDate || undefined, toDate: toDate || undefined });
  const money = (value: string) => new Intl.NumberFormat(locale === "ar" ? "ar-JO" : "en-JO", { style: "currency", currency: "JOD" }).format(Number(value)); const reset = () => setPage(1);
  return <div className="space-y-4"><div className="rounded-3xl border bg-card p-4"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-[1fr_12rem_12rem_10rem_10rem_auto]"><div className="relative"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(e) => { setSearch(e.target.value); reset(); }} placeholder={t("orders.search")} className="rounded-full ps-9" /></div><Select value={status} onValueChange={(value) => { if (value) { setStatus(value as typeof status); reset(); } }}><SelectTrigger className="w-full rounded-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">{t("orders.allStatuses")}</SelectItem>{statuses.map((item) => <SelectItem key={item} value={item}>{t(`statuses.${item}`)}</SelectItem>)}</SelectContent></Select><Select value={payment} onValueChange={(value) => { if (value) { setPayment(value as typeof payment); reset(); } }}><SelectTrigger className="w-full rounded-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ALL">{t("orders.allPayments")}</SelectItem>{payments.map((item) => <SelectItem key={item} value={item}>{t(`payments.${item}`)}</SelectItem>)}</SelectContent></Select><Input type="date" value={fromDate} onChange={(e) => { setFromDate(e.target.value); reset(); }} aria-label={t("orders.fromDate")} className="rounded-full" /><Input type="date" value={toDate} onChange={(e) => { setToDate(e.target.value); reset(); }} aria-label={t("orders.toDate")} className="rounded-full" /><Button render={<Link href={`/${locale}/shop-owner/orders/new`} />} className="rounded-full"><Plus className="size-4" />{t("orders.new")}</Button></div></div>
  {isLoading ? <div className="grid gap-3">{Array.from({ length: 5 }).map((_, i) => <Skeleton key={i} className="h-28 rounded-3xl" />)}</div> : isError || !data ? <Card className="rounded-3xl"><CardContent className="flex min-h-64 flex-col items-center justify-center gap-3"><ClipboardList className="size-9 text-destructive" /><p>{t("orders.error")}</p><Button onClick={() => refetch()}>{t("actions.retry")}</Button></CardContent></Card> : data.orders.length === 0 ? <Card className="rounded-3xl"><CardContent className="flex min-h-64 items-center justify-center">{t("orders.empty")}</CardContent></Card> : <><div className="grid gap-3">{data.orders.map((order) => <Link key={order.id} href={`/${locale}/shop-owner/orders/${order.id}`} className="grid gap-3 rounded-3xl border bg-card p-5 transition-all hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-mono text-xs text-muted-foreground">#{order.id.slice(0, 8)}</p><h3 className="mt-1 font-semibold">{order.customerName}</h3><p className="line-clamp-1 text-sm text-muted-foreground">{order.customerAddress}</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="rounded-full">{t(`statuses.${order.status}`)}</Badge><Badge variant="secondary" className="rounded-full">{t(`payments.${order.paymentStatus}`)}</Badge></div><div className="sm:text-end"><p className="font-semibold">{money(order.customerTotal)}</p><p className="text-xs text-muted-foreground">{new Intl.DateTimeFormat(locale === "ar" ? "ar-JO" : "en-GB", { dateStyle: "medium" }).format(new Date(order.createdAt))}</p></div></Link>)}</div><div className="flex items-center justify-between rounded-full border bg-card px-4 py-2"><p className="text-sm text-muted-foreground">{t("orders.showing", { shown: data.orders.length, total: data.pagination.total })}</p><div className="flex gap-2"><Button size="icon" variant="outline" className="rounded-full" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}><ChevronLeft className="rtl:rotate-180" /></Button><span className="flex min-w-16 items-center justify-center text-sm">{page} / {Math.max(data.pagination.totalPages, 1)}</span><Button size="icon" variant="outline" className="rounded-full" disabled={page >= data.pagination.totalPages} onClick={() => setPage((p) => p + 1)}><ChevronRight className="rtl:rotate-180" /></Button></div></div></>}</div>;
}
